### ISSUE TITLE
Translations not updated frequently

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-pages#139]
I had made a mistake with a link, I had fixed it as soon as I noticed it, but that was some days ago and the translations seems not to be updated yet, see the broken GDPR link: https://delta.chat/es/

**Comment by r10s** [comment]
i've just updated the translations.

currently, it's a manual process, basically `t-dance pull` has to run locally from the `tools` directory and there are only few persons that have set up the tools needed on their machines.

so, if someone is up to improve this process, this would be very welcome :)

**Comment by ghost** [comment]
Does anything speak against a github action which executes something like `t-dance.sh pull && t-dance.sh push` and commits it to master? maybe after each pull request?

I'm currently doing that manually from time to time, and take a look at the diff before I push it to GitHub. But if there is never any problem, we could just automate this of course.

**Comment by r10s** [comment]
i'd say a `t-dance.sh push` should always work after commits/merges to master - unless we break things badly. but then it is our fault :)  

not sure about a `t-dance.sh pull` - doing that too fast or too often can be annoying for the translators as "their" language page is full of english texts then - so, maybe better do that manually, once or twice a week or so. this also gives us the option do do a quick `diff` and see if there are rough errors.

we can see how this works, maybe with the automated `t-dance.sh push`, translations will be faster so that we can rethink doing also the pull automatically.

**Comment by Simon-Laux** [comment]
we could either only push reviewed language strings from transifex or the action could just see if jekyll build still works afterwards.

**Comment by ghost** [comment]
To keep in mind: when someone does a `tools/t-dance.sh pull` locally, and pushes this to master, the github action from #285 gets executed again, and pushes them to transifex.
