### ISSUE TITLE
Lost changes from gdpr-international.md

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-pages#152]
This commit removed the include statements ("to make it translatable") but pasted a version different from the originally included file.

https://github.com/deltachat/deltachat-pages/commit/bb6586200d59d93ce31170959ed1e43f5e026bd0#diff-0c37c3d787c580808fced0be2a0a478b

**Comment by testbird** [comment]
Nah, seems it was not the commit above but some other commit, I don't find.

But this is the pull request with the changes that have been overwritten.
https://github.com/deltachat/deltachat-pages/pull/89

**Comment by testbird** [comment]
Not sure if this is the latest version, but it contains some lost changes.

https://github.com/deltachat/deltachat-pages/blob/e0011eda2b1c8aa19ce55c14db903e3ef2d91dd4/_includes/gdpr-international.md

**Comment by r10s** [comment]
when i compare the green (new) parts of https://github.com/deltachat/deltachat-pages/pull/89 and the current state of https://delta.chat/en/gdpr, this does not look to me as if there is something really missing.

eg. the proposed sentences "Does not require any **consent** (article 7 GDPR) from the users or their contacts (data subjects), because no address-book-data is transmitted" or "Can be used without requiring a contract or instructions from any controller (organisation), because no additional third party will process the E-Mail related personal data." are in the most recent version.

there seems to be some more recent changes, but in general, the correct file seems to be picked up.

**Comment by testbird** [comment]
I didn't add or change new text  (I am no lawyer), but tried to sort out the sentences, and grammar, and added more descriptive (sub)titles to make it more readable.

**Comment by testbird** [comment]
I don't know how to find the actual last gdpr-international.md version, to try pasting it into the editor for a diff.

**Comment by testbird** [comment]
I think I found the latest version now...
