### ISSUE TITLE
Improve translation system

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#197]
Ideas:
- move translated pages into a folder -> like _pages. (requires config.yml and t-dance changes) 
- gitignore the translated pages to make prs more workable. We can download the translations in the website building process before jekyll
- find out if there is a more efficient way of creating the po files when using html (that we don't have all the tags in the po files)

**Comment by Simon-Laux** [comment]
maybe we should use http://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/html2po.html for conversion instead of txt2po and use html. In future we would need our own converter that ignores html logic, jekyll liquid logic and markdown logic

_Originally posted by @Simon-Laux in https://github.com/deltachat/deltachat-pages/pull/194#issuecomment-554095186_

**Comment by ghost** [comment]
To revive this issue, and come to a mutual understanding of the problem: if I understand it correctly, did you want to address these problems?

1. It's not obvious to contributors which files they can touch, and which are generated automatically
2. PRs are cluttered by translations, and hard to review
3. .po files are annoying
4. keep translators from accidentally translating liquid tags

Is this correct? Because in this case I would argue that:

1. Most contributors should of course only touch the `/en` and the `/_posts` folder. The README.md is quite explicit on this, and the people who review PRs can point them there in case they missed it.
2. The best solution to this IMHO is to execute t-dance.sh only on the master branch, and only after PRs are merged. But let's discuss this in #139.
3. Well, #249 luckily took care of this :)
4. I think this happened once or twice in the last months; and we always found out and could fix it before it caused really big problems. It's not cool, but not pressing enough to throw hours of work against the problem, to give up on markdown, or to add tremendous complexity to this repository.

**Comment by r10s** [comment]
so, as a summary, most things are solved, maybe not perfectly, but okayish.
in general, i am not up for larger changes in this area just now anyway, we should fix the bugs with yml etc. but, for now leave the coarse structure as is.

so i think we should close this issue for now and open more specific ones as needed.

**Comment by Simon-Laux** [comment]
>  to give up on markdown

I never implied that... Do we have a way to inform the translators to not translate liquid tags?

**Comment by r10s** [comment]
> Do we have a way to inform the translators to not translate liquid tags?

you can add comments to every string when logged into transifex. translators also make use of this, there are discussions and quesions about strings, so it makes sense to have a look at that from time to time anyway.

not sure how/if this can work automatically (it works with the android strings.xml by adding a remark directly before the string - this is shown on transifex - not sure about .po, though)
