### ISSUE TITLE
Consider using support forum for Howto, and developer-news etc

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-pages#255]
Just came across https://community.e.foundation/ and suggest to consider developing our support forum into a similar direction, notably: HowTos (multi-device, verified groups, ...), and developer-news i.e. news we are currently sending to the mailing list for example, or keeping for ourselves.

**Comment by r10s** [comment]
i think, this is a good idea, also it is much easier to $do sth there, you do not have to think about later translations etc.

all we need is probably new categories?

and yes, add the mailing list post, or at least some selected ones, in the forum is probalby a good idea. maybe we can also add some of the most ones.

also, the default view of  https://community.e.foundation/  is nice - but this can be another step.

**Comment by ghost** [comment]
For background info, @Simon-Laux and I already discussed the idea of a "Guide" category in https://support.delta.chat/t/add-guide-category/531/4 

Back then I was opposed to the idea, because I thought guides would fit better on the page; it's unlikely though that much will happen there, and the treshold for contributions by others is lower on the forum. So meanwhile I'd say, why not.

A "News" category is also a good idea. In my private "Blogpost writing checklist" there is already a checkbox for "post it on the forum" ;)

Keep in mind that when we set up the forum, we wanted to have as few categories as possible. But the need for those two categories showed itself in the past, so I'm for it.

**Comment by Simon-Laux** [comment]
Please discuss this on the forums site feedback category and not here.

**Comment by hpk42** [comment]
it's an overall arrangement thing ... not starting a support forum thread right now about it but thanks for the hint, and the feedback.

**Comment by ghost** [comment]
I created a topic for the News category and updated the Guide category topic, so we can discuss it there :)

https://support.delta.chat/t/add-news-category/757
