### ISSUE TITLE
FAQ entry on releasing a fork of deltachat

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#359]
I should outline a few fair use rules. in essence some core guidelines how to not start legal trouble with us/deltachat/merlinux

These are the ones that currently come to my mind, please comment bellow to add things I missed.

- Do not use the trademarked name `DeltaChat`
- Do not sell a fork.*
- Give credit to the project you forked, or if you only use our core tell your users about that (`powered by deltachat-core` or/and a sentence with link on your about/credits/settings page/screen)
- respect the licenses of the projects
- you can not release an fork of our iOS app without our explicit permission.
- If you have questions about these rules or want to be sure that your project is not in violation, contact us under delta@merlinux.eu

\* If you want to discuss white-labeling or releasing a paid fork/alternative app contact us under delta@merlinux.eu

**Comment by r10s** [comment]
stale issue, also not sure if that is really something for the FAQ, i mean the "F" is for "Frequently", and FAQ also goes to the local help, so that is more for end users.

maybe this is more sth. for the README.md in the respective repositories? or maybe for the imprint?

anyway, as no-one seems to work on that (and we want to track things someone is actually working on and bugs in the issue tracker only), i am closing this.
