### ISSUE TITLE
update gdpr page

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-pages#430]
We need to add an section about location streaming used on Android, so that future app updates will be accepted in googles review process. 
The gdpr page is linked from the play store and is used as our 'privacy policy' page for DC Android.

**Comment by cyBerta** [comment]
related issue: https://github.com/hpk42/bg-deltachat/issues/153

**Comment by Simon-Laux** [comment]
something like that? because its a table it might make sense to create it as either html so the lines are separate and better to translate or as include-element with key-value translations like the download boxes (I would prefer the latter one as it is cleaner and the keys could already be telling to translators like `permission_camera_explanation`). 

# App Permissions

What Permissions the DeltaChat app asks for and what it uses them for.


| Permission | Purpose |
|------------|---------|
| Camera     | Take pictures to send them and to scan QR codes |
| Microphone | To record voice-messages |
| Location   | To send your location as attachment |
| Background Location | For the optional Location streaming feature that allows to share the own location with contacts for a specified time period |
| Storage | To save attachments |
| Contacts | To import your existing contacts into the app, they are NOT uploaded anywhere |

**Comment by r10s** [comment]
maybe, however, technically i would try to keep the information in one document, to make processing by privacy experts etc. easier. and not split it into single strings or so.

otoh, the current gdpr and its "high-level overview" was already accepted by google before, so it is not that bad. so minimal effort would be to just add a sentence with the missing bit wrt background location (the example from above is probably not even specific enough, one has to read though and understand what google really wants here)

**Comment by r10s** [comment]
closed by https://github.com/deltachat/deltachat-pages/pull/441
