### ISSUE TITLE
Update user stories and voices

### ISSUE THREAD

**Issue by Yettte** [deltachat/deltachat-pages#483]
Just had a look at Delta Chat's Website, user stories and voices. Could be nice to add some up to date stories, since there are many! Yeaaah! 

To find up to date user voices see for example:

https://masto.1146.nohost.me/@lps/106303722917783273 - EDIT 2023: this refers to jit.si, which, in that generalisation, is meanwhile not the best videochat provider as it requires login

http://www.blindzeln.org/index.php - EDIT 2023: this does not refer to delta - or the page has changed meanwhile

**Comment by missytake** [comment]
- [ ] https://oc.todon.fr/@borispaing/106607795144753681 - EDIT 2023: outdated as we meanwhile have user switching
- [ ] https://fosstodon.org/@totoroot/106580007213197440 - EDIT 2023: stale
- [ ] https://mamot.fr/@matiu_bidule/106616855046373526 - EDIT 2023: 404

**Comment by missytake** [comment]
- [ ] https://social.anoxinon.de/@7daq0/106874725177881063 - EDIT 2023: 404
- [ ] https://framapiaf.org/@brab/106929940631242693 - EDIT 2023: je ne parle pas français
- [ ] https://mamot.fr/@matiu_bidule/106969064554286011 - EDIT 2023: 404
- [ ] https://mamot.fr/@matiu_bidule/107044666430952413 - EDIT 2023: 404
- [ ] https://chaos.social/@realramnit/107093087083880033 - EDIT 2023: could be used, however,  the discussions is pretty old, does not add much and there are probably better and more recent ones

**Comment by missytake** [comment]
Hm, it seems to me the purpose of the page is not really to make the most recent praise public, but rather cover different topics/features/use cases. So the dates should be de-emphasized in my opinion; maybe we only tell the year for the comments without a source? And the first comment should be something with a source link?

**Comment by Yettte** [comment]
I have another good one that kind of covers new directions in DC development.
https://101010.pl/@michal/107107322703871076 - EDIT 2023: already added

**Comment by Yettte** [comment]
> Hm, it seems to me the purpose of the page is not really to make the most recent praise public, but rather cover different topics/features/use cases. So the dates should be de-emphasized in my opinion; maybe we only tell the year for the comments without a source? And the first comment should be something with a source link?

I think that's a good idea. Posting things by topic rather than by date gives much more info to people interested in user opinions.

**Comment by hpk42** [comment]
IMO it makes sense to go through the links and see what makes sense for adding under an existing or new headline. At best in a single PR that modifies/adds, thereby closing this issue here.  Stating the year of the feedback is not so bad i think.  For example could have a connectivity-view related headline (i don't speak french but the screenshot is about it) and mention 2021.  Adding more recent praise (2021) as substitute for 2020 ones is also useful.  It feels different to have recent quotes.

**Comment by r10s** [comment]
i checked all links:
- most are 404 or otherwise outdated as years old, projecting things that look a bit off if added 3 years later
- some are already added

closing this issue, it seems better to add more recent things. i think, in the future, it makes more sense to do a pull request instead of collecting links that no one really takes care for
