### ISSUE TITLE
Problem with attached files

### ISSUE THREAD

**Issue by westsibe** [deltachat/deltachat-pages#49]
1. Impossible send text message with attached file.
2. If I send picture: in another e-mail program I see picture and BASE-64 code (as text).

Android 4.4.2, ARMv7, MTK6582.

**Comment by westsibe** [comment]
#1 need make;
#2 fixed.

**Comment by westsibe** [comment]
Sorry, #2 is not fixed, if my status is empty.

**Comment by r10s** [comment]
Hi westsibe,

thank you for your posts.

However, if you want someone to work on the problem, we would probably need more information. And the issue should be moved to the correct repository. Please go to https://github.com/deltachat/deltachat-android/issues (assuming the problem is Android-related) and look for similar issues or click on "New issue". There, read the contribution guidelines and the pre-filled text. HTH :)

**Comment by westsibe** [comment]
Yes, this talk about Delta Chat ver.0.9.9 for Android.
