### ISSUE TITLE
translated sites are out of date

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#600]
for example the money donation site is not separate yet
and download button is missing on homepage.

also after updating the `https://delta.chat/donate` redirect should be removed, so that it leads to the right donation website.

**Comment by r10s** [comment]
there is already a pr, https://github.com/deltachat/deltachat-pages/pull/599 , however, there are still some issues.

in general, it is fine if the translations come a bit later. that way, there is a chance we really get translations and do not a new "english" page to some otherwise good looking translation. i would not call this a bug therefore, but i also do not really mind :) thanks for reminding, however!

**Comment by rosano** [comment]
I'm looking at the website translations and it seems the English source for `/contribute` still references Twitter on Transifex while it seems to have been removed from the site. Does something have to be synced before the strings can be edited? I wanted to work on other languages for the site.

**Comment by Simon-Laux** [comment]
bump: still an issue

**Comment by rosano** [comment]
I wanted to work on this but (perhaps erroneously) was waiting for #599 to be merged, but it seems to not be so urgent anyway.

**Comment by r10s** [comment]
seems `donate` is just missing at all, i am on fixing that now
