### ISSUE TITLE
avoid relative links in the offline help

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-pages#649]
relative links in the help needs to be converted to absolute links, this is easily done, but also easily overseen or done wrong (even on delta.chat, see #648).

we should error out in create-local-help.py if there is any link at the end not startiing with `https` or `#` or are otherwise whitelisted.

**Comment by missytake** [comment]
It has advantages to use relative links in the *online* help, because then the link actually directs to the translated page instead of the english page, if the link is not translated correctly as well (and we can absolutely not rely on that).

Maby the script can convert the relative links to absolute links?

**Comment by r10s** [comment]
> Maby the script can convert the relative links to absolute links?

yip, the script is already doing that, eg. for `serverguide`.

but the blog links are not present in other languages, so, for them, an absolute path does not really hurt (and an relative one is even wrong unless using `../en/blog-url`

however, i also aim to check the links in the script more carefully, so that we do not manifest errors in the offline help. the help should just be able to use all kind of _working_ links, the script will convert them.

**Comment by r10s** [comment]
fixed by #651
