### ISSUE TITLE
HTML anchor part "#changelogs" mentioned in device message does not work for non-English websites

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-pages#698]
- Operating System (Linux/Mac/Windows/iOS/Android):
Android 11.

- Delta Chat Version:
1.38.2.

- Expected behavior:
The link `https://get.delta.chat/#changelogs` works for localized (non-English) web content, too.

- Actual behavior:
The link `https://get.delta.chat/#changelogs` does not work for localized (non-English) web content.

- Steps to reproduce the problem:
-- Set the language to German in Delta Chat as well as your web browser app on top for your favourite web content.
-- Open the device message ("Systemnachricht") "1.38 ist da".
-- Tap on the link `https://get.delta.chat/#changelogs`. (Result: The web browser app opens and displays the website well, but does not jump to the section "Änderungsprotokolle", the German changelog, due to the missing anchor part `#changelogs` on the site. Instead, the respective German anchor part is named `#änderungsprotokolle`.)

- Screenshots:
N/A.

- Logs:
N/A.

**Comment by r10s** [comment]
i think we need to explicitly name the anchor in [`en/download.md`](https://github.com/deltachat/deltachat-pages/blob/master/en/download.md?plain=1#L7) so that it survives translations (that pattern works already for  [`en/help.md`](https://github.com/deltachat/deltachat-pages/blob/master/en/help.md?plain=1#L446): in german, that has the same anchor name: [`de/help.md`](https://github.com/deltachat/deltachat-pages/blob/master/de/help.md?plain=1#L332))

**Comment by r10s** [comment]
should work now, see eg. https://delta.chat/uk/download#changelogs (which is a redirect target from the https://get.delta.chat/#changelogs mentioned above, for testing, do not forget to invalidate caches)

**Comment by gerryfrancis** [comment]
@r10s Yes, it works fine now, I checked with the link in the device message that I mentioned above. Thank you for the fast fix! :)
