### ISSUE TITLE
Deltachat desktop is long not compatible with ubuntu 18 anymore

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#724]
See https://github.com/deltachat/deltachat-desktop/issues/3378

**Comment by link2xt** [comment]
This issue is about updating the line "Minimal requirements: Android 4.1 Jelly Bean or iOS 11, iPhone 5s or iPad 5/Air/Mini or Windows 7, macOS 10.11 El Capitan, Ubuntu 18.04, Fedora 29 or Debian 10 or compatible systems."

But we can as well just fix Ubuntu 18.04 compatibility: https://github.com/deltachat/deltachat-core-rust/pull/4686
