### ISSUE TITLE
FAQ Entry: what is FILL 500 and what's the worst that can happen without it

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-pages#743]
alternative title: why are webxdc loading so slow?

It is our fill500 workaround that we need to block the webxdc apps from leaking data via WebRTC, see the blogpost (link it https://delta.chat/en/2023-05-22-webxdc-security#fill500-disabling-webrtc-on-chromium).

It is present on deltachat desktop and deltachat android, but not deltachat iOS.

If it takes too long or even crashes your android device, make sure to upgrade your chromium app to update your web view version. (on older android devices there is still a web view app).

[after we implemented ways to disable it globally]
What's the worst that can happen when you disable this security measure?

- leaked ip address
- leaked email address and displayname
- leaked data that you put into the webxdc app.
- more? investigate?

**Comment by r10s** [comment]
> why are webxdc loading so slow?

is it _so slow_ for the majority of users that this becomes a frequent question many user have? or is it just some delay and ppl do not really take care of?

things are hard to explain anyways, the  option to disable FILL500 is not even existent and we should take care not to show our worse things only and to scare users in an emerging ecosystem we want to grow

but anyways, we do not want to track possible amendment of the faq in the issue tracker waiting to get stale  (each dev could otherwise easily open several dozens ones). as discussed, this repo is not a repo where one can "delegate" things to others in the hoping, someone will take care then

if you still think it is important enough, please do a pr with a short note that links to the blog entry or to a new forum entry. i would assume, that this would have cost less time that writing these two posts

**Comment by Simon-Laux** [comment]
> is it so slow for the majority of users that this becomes a frequent question many user have? or is it just some delay and ppl do not really take care?

on some chrome version it freezes your whole android device (happened to me once, was really annoying).

Anyways this was more of a reminder of a discussion I had with Holger.
