### ISSUE TITLE
Move a security related text block from "Miscellaneous" to "Encryption and Security" in FAQ's

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-pages#827]
The whole text block "Was Delta Chat independently audited for security vulnerabilities?" should be moved from "Miscellaneous" to "Encryption and Security" on the FAQ website.

**Comment by r10s** [comment]
makes sense, thanks for noticing (and moving text blocks around fortunately do not trigger retranslations :)

are you up to make a PR? (needed for english only, the translations will follow on next [`t-dance`](https://github.com/deltachat/deltachat-pages/blob/master/tools/t-dance.sh)) otherwise i am happy to do one as well
